name: ChairEco
version: "1.0"
author: RedChair
main: tech.cheating.chaireco.Economy

commands:
  balance:
    description: Tells you how much money
    usage: /balance (playername)

  pay:
    description: Allows you to pay someone money
    usage: /pay otherplayer amountofmoney (reason)